version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
    container_name: sailsnap-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./src/backend
    container_name: sailsnap-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sailsnap
      SPRING_DATASOURCE_USERNAME: sailsnap
      SPRING_DATASOURCE_PASSWORD: sailsnappw
      AWS_REGION: ${AWS_REGION}
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

volumes:
  pgdata:
