spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update

# FFmpeg paths
ffmpeg.path=/usr/bin/ffmpeg
ffprobe.path=/usr/bin/ffprobe

# Later, in production or Docker, you can override these values with environment variables:
# export FFMPEG_PATH=/app/ffmpeg/ffmpeg
# export FFPROBE_PATH=/app/ffmpeg/ffprobe
